spring.application.name=spring-boot-rest-api

spring.datasource.url=jdbc:mysql://localhost:3306/springbootrestapi
spring.datasource.username=root
spring.datasource.password=

spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update


